{% set version = "2.0.10" %}

package:
  name: bob.learn.boosting
  version: {{ version }}

source:
  fn: bob.learn.boosting-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.learn.boosting/bob.learn.boosting-{{ version }}.zip
  md5: 2666fcac9bd2b375326d7c78af80ee7c

build:
  entry_points:
    - boosting_example.py = bob.learn.boosting.examples.mnist:main
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - numpy
    - scipy
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.63.*
    - cmake
    - pkg-config

  run:
    - python
    - numpy
    - scipy
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.63.*

test:
  commands:
    - boosting_example.py --help
    - nosetests -sv bob.learn.boosting

  imports:
    - bob
    - bob.learn
    - bob.learn.boosting
    - bob.learn.boosting.examples
    - bob.learn.boosting.tests

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GPLv3
  summary: Boosting framework for Bob

extra:
  recipe-maintainers:
    - 183amir
